// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package works.weave.socks.cart.cartserver.tars.cart;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface CartsControllerServant {

	public CartTars get(String customerId);

	public void delete(String customerId);

	public void mergeCarts(String customerId, String sessionId);
}
