// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package works.weave.socks.cart.cartserver.tars.cart;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ItemsControllerServant {

	public ItemTars get(String customerId, String itemId);

	public java.util.List<ItemTars> getItems(String customerId);

	public ItemTars addToCart(String customerId, ItemTars item);

	public void removeItem(String customerId, String itemId);

	public void updateItem(String customerId, ItemTars item);
}
