// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package works.weave.socks.orders.orderserver.tars.order;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class AddressTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String number = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String street = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String city = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String postcode = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String country = "";

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public AddressTars() {
	}

	public AddressTars(String id, String number, String street, String city, String postcode, String country) {
		this.id = id;
		this.number = number;
		this.street = street;
		this.city = city;
		this.postcode = postcode;
		this.country = country;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(number);
		result = prime * result + TarsUtil.hashCode(street);
		result = prime * result + TarsUtil.hashCode(city);
		result = prime * result + TarsUtil.hashCode(postcode);
		result = prime * result + TarsUtil.hashCode(country);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AddressTars)) {
			return false;
		}
		AddressTars other = (AddressTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(number, other.number) &&
			TarsUtil.equals(street, other.street) &&
			TarsUtil.equals(city, other.city) &&
			TarsUtil.equals(postcode, other.postcode) &&
			TarsUtil.equals(country, other.country) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != number) {
			_os.write(number, 1);
		}
		if (null != street) {
			_os.write(street, 2);
		}
		if (null != city) {
			_os.write(city, 3);
		}
		if (null != postcode) {
			_os.write(postcode, 4);
		}
		if (null != country) {
			_os.write(country, 5);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.number = _is.readString(1, false);
		this.street = _is.readString(2, false);
		this.city = _is.readString(3, false);
		this.postcode = _is.readString(4, false);
		this.country = _is.readString(5, false);
	}

}
